site_name: NexaORM
site_url: https://example.com/
site_author: Fortunatus KIDJE (v1p3r75)
site_description: >-
  NexaORM is a modern PHP Object-Relational Mapping (ORM) library designed
  to simplify database interactions and streamline the development of PHP applications. 
site_dir: build

repo_name: NexaORM
repo_url: https://github.com/v1p3r75/NexaORM


nav:

  - Get Started : index.md
  - Configuration : configuration.md
  - Entities : entities.md
  - Attributes : attributes.md
  - Models : models.md
  - Collections : collections.md
  - Migrations : migrations.md
  - Contributing : contributing.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.expand
    - navigation.footer
    - content.code.copy
    - content.code.select

    - search.highlight
    - search.share
    - search.suggest

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
  - pymdownx.superfences 


copyright: Copyright &copy; 2024 - NexaORM
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/v1p3r75/

    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/fortunatus-ek/

    - icon: fontawesome/brands/x-twitter  
      link: https://twitter.com/elfriedv16
