site_name: NexaORM
site_url: https://example.com/
nav:

  - Get Started : index.md
  - Configuration : configuration.md
  - Entities : entities.md
  - Attributes : attributes.md
  - Models : models.md
  - Collections : collections.md
  - Migrations : migrations.md
  - Contributing : contributing.md

theme:
  name: material
  highlightjs: true
  hljs_languages:
    -php